name: Go Build and Release

on:
  push

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Install node and curl
        run: |
          apk update
          apk add --no-cache curl nodejs

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: Get dependencies
        run: go mod tidy

      - name: Build project
        run: go build
      
      - name: Update Server by 1panel
        env:
            PANEL_API_KEY: ${{ secrets.PANEL_API_KEY }}
            PANEL_URL: ${{ secrets.PANEL_URL }}
            APP_NAME: "CatBot"
        run: chmod +x script/update.sh && ./script/update.sh